# VM-оверрайды для Hyprland (VirtualBox/Vmware): софтовый рендерер (llvmpipe)
# не тянет blur/shadow/animations — отключаем всё тяжёлое.

monitor = ,preferred,auto,1

general {
    gaps_in = 1
    gaps_out = 3

    border_size = 1

    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)

    resize_on_border = false
    allow_tearing = false

    layout = master
}

decoration {
    rounding = 0
    rounding_power = 1

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = false
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
}

env = WLR_NO_HARDWARE_CURSORS,1